import type { CaseSnapshot } from '../domain/case-state';

export const SYNTHETIC_CASE_SNAPSHOT: CaseSnapshot = {
  caseId: 'synthetic-family-case',
  generatedAt: '2026-08-20T12:00:00.000Z',
  timeline: [
    {
      id: 'evt-2023-old-agreement',
      occurredAt: '2023-02-10T10:00:00.000Z',
      kind: 'agreement',
      topic: 'samvaer',
      title: 'Tidligere samværsaftale',
      summary: 'En ældre aftale fastlagde weekend-samvær efter et andet mønster.',
      sourceIds: ['doc-2023-old-contact'],
      disputed: false,
    },
    {
      id: 'evt-2025-current-agreement',
      occurredAt: '2025-04-12T10:00:00.000Z',
      kind: 'agreement',
      topic: 'samvaer',
      title: 'Ny skriftlig samværsaftale',
      summary: 'Weekendsamvær fredag kl. 17 til søndag kl. 18. Ændringer kræver skriftlig aftale.',
      sourceIds: ['doc-2025-current-contact'],
      disputed: false,
    },
    {
      id: 'evt-2026-lawyer-proposal',
      occurredAt: '2026-06-03T09:00:00.000Z',
      kind: 'proposal',
      topic: 'samvaer',
      title: 'Forslag om torsdag kl. 16',
      summary: 'Advokatbrev foreslår ændret starttidspunkt, men beder om accept.',
      sourceIds: ['doc-2026-lawyer-proposal'],
      disputed: false,
    },
    {
      id: 'evt-2026-message-claim',
      occurredAt: '2026-08-01T17:42:00.000Z',
      kind: 'claim',
      topic: 'samvaer',
      title: 'Påstand om at torsdag er aftalt',
      summary: 'Den anden forælder skriver, at torsdag kl. 16 allerede er aftalt.',
      sourceIds: ['msg-2026-08-01-parent-b'],
      disputed: true,
    },
  ],
  currentState: [
    {
      id: 'state-old-weekend',
      topic: 'samvaer',
      summary: 'Tidligere weekendordning fra 2023.',
      authority: 'signed_party_agreement',
      status: 'superseded',
      sourceRefs: [{ sourceId: 'doc-2023-old-contact' }],
      supersedesEntryIds: [],
      proposedBy: 'deterministic_rule',
    },
    {
      id: 'state-current-weekend',
      topic: 'samvaer',
      summary: 'Weekendsamvær fredag kl. 17:00 til søndag kl. 18:00. Ændringer kræver skriftlig aftale.',
      authority: 'signed_party_agreement',
      status: 'confirmed',
      sourceRefs: [{ sourceId: 'doc-2025-current-contact', excerpt: 'fredag kl. 17:00 til søndag kl. 18:00' }],
      supersedesEntryIds: ['state-old-weekend'],
      proposedBy: 'deterministic_rule',
      confirmedBy: 'deterministic_rule',
    },
    {
      id: 'state-thursday-proposal',
      topic: 'samvaer',
      summary: 'Forslag om at fremtidigt samvær starter torsdag kl. 16:00.',
      authority: 'lawyer_position',
      status: 'candidate',
      sourceRefs: [{ sourceId: 'doc-2026-lawyer-proposal', excerpt: 'foreslår ... torsdag kl. 16:00' }],
      supersedesEntryIds: [],
      proposedBy: 'ai',
    },
  ],
};
